
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zachariah
 */
public class JavaPOS extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        jColorChooser4 = new javax.swing.JColorChooser();
        jColorChooser5 = new javax.swing.JColorChooser();
        jColorChooser6 = new javax.swing.JColorChooser();
        jColorChooser7 = new javax.swing.JColorChooser();
        jColorChooser8 = new javax.swing.JColorChooser();
        jPanel2 = new javax.swing.JPanel();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbtnRemove = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jtxtBarCode = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbtngreencapsicum = new javax.swing.JButton();
        jbtngreenapples = new javax.swing.JButton();
        jbtnlemons = new javax.swing.JButton();
        jbtnimportedoranges = new javax.swing.JButton();
        jbtnmixedlettuce = new javax.swing.JButton();
        jbtnlime = new javax.swing.JButton();
        jbtnpineapples = new javax.swing.JButton();
        jbtnpotatoes = new javax.swing.JButton();
        jbtnredapples = new javax.swing.JButton();
        jbtnredcabbage = new javax.swing.JButton();
        jbtnredcapsicum = new javax.swing.JButton();
        jbtnredonion = new javax.swing.JButton();
        jbtnspringonions = new javax.swing.JButton();
        jbtnstrawberry = new javax.swing.JButton();
        jbtntomatoes = new javax.swing.JButton();
        jbtnwhitecabbage = new javax.swing.JButton();
        jbtnwhiteonions = new javax.swing.JButton();
        jbtnyellowcapsicum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 70));

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 70));

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 70));

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 70));

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, 70));

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 80, 70));

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 70));

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 80, 70));

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 80, 70));

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, 70));

        jbtnDot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 80, 70));

        jbtnC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 280, 400));

        jTable1.setBackground(new java.awt.Color(204, 255, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 270, 360));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnRemove.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 110, 40));

        jbtnPay.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        jbtnExit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 240, 30));

        jbtnPrint.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 40));

        jbtnReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 110, 40));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 260, 140));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Tax");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel6.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, -1));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel6.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 160, -1));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 160, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 140));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Cash");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Payment Method");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Change");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel7.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 180, -1));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel7.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, -1));

        jcboPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });
        jPanel7.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 380, 140));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 1370, 160));

        jtxtBarCode.setFont(new java.awt.Font("C39HrP24DlTt", 0, 36)); // NOI18N
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 270, 50));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtngreencapsicum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtngreencapsicum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/green capsicum.jpg"))); // NOI18N
        jbtngreencapsicum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngreencapsicumActionPerformed(evt);
            }
        });
        jPanel1.add(jbtngreencapsicum, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 90));

        jbtngreenapples.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtngreenapples.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/green apples.jpg"))); // NOI18N
        jbtngreenapples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngreenapplesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtngreenapples, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 90));

        jbtnlemons.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnlemons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lemons.jpg"))); // NOI18N
        jbtnlemons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlemonsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnlemons, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, 90));

        jbtnimportedoranges.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnimportedoranges.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imported oranges.jpg"))); // NOI18N
        jbtnimportedoranges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimportedorangesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnimportedoranges, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 100, 90));

        jbtnmixedlettuce.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnmixedlettuce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mixed lettuce.jpg"))); // NOI18N
        jbtnmixedlettuce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmixedlettuceActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnmixedlettuce, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 100, 90));

        jbtnlime.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnlime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lime.jpg"))); // NOI18N
        jbtnlime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlimeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnlime, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 100, 90));

        jbtnpineapples.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnpineapples.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pineapples.jpg"))); // NOI18N
        jbtnpineapples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpineapplesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnpineapples, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 90));

        jbtnpotatoes.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnpotatoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/potatoes.jpg"))); // NOI18N
        jbtnpotatoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpotatoesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnpotatoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, 90));

        jbtnredapples.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnredapples.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red apples.jpg"))); // NOI18N
        jbtnredapples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnredapplesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnredapples, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 100, 90));

        jbtnredcabbage.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnredcabbage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red cabbage.jpg"))); // NOI18N
        jbtnredcabbage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnredcabbageActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnredcabbage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 100, 90));

        jbtnredcapsicum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnredcapsicum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red capsicum.jpg"))); // NOI18N
        jbtnredcapsicum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnredcapsicumActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnredcapsicum, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 100, 90));

        jbtnredonion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnredonion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red onions.jpg"))); // NOI18N
        jbtnredonion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnredonionActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnredonion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 100, 90));

        jbtnspringonions.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnspringonions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/spring onion.jpg"))); // NOI18N
        jbtnspringonions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnspringonionsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnspringonions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 90));

        jbtnstrawberry.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnstrawberry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/strawberry.jpg"))); // NOI18N
        jbtnstrawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnstrawberryActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnstrawberry, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 100, 90));

        jbtntomatoes.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtntomatoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tomatoes.jpg"))); // NOI18N
        jbtntomatoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntomatoesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtntomatoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, 90));

        jbtnwhitecabbage.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnwhitecabbage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white cabbage.jpg"))); // NOI18N
        jbtnwhitecabbage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnwhitecabbageActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnwhitecabbage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 100, 90));

        jbtnwhiteonions.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnwhiteonions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white onion.jpg"))); // NOI18N
        jbtnwhiteonions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnwhiteonionsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnwhiteonions, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 100, 90));

        jbtnyellowcapsicum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnyellowcapsicum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/yellow capsicum.jpg"))); // NOI18N
        jbtnyellowcapsicum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnyellowcapsicumActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnyellowcapsicum, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 100, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//=======================Functions==================================================================
    public void ItemCost()
    {
        double sum = 0;
        
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        
        double cTax = (cTotal1 * 0)/100;
        String iTaxTotal = String.format("Ksh %.2f", cTax);
        jtxtTax.setText(iTaxTotal) ;
        
        String iSubTotal = String.format("Ksh %.2f", cTotal1);
        jtxtSubTotal.setText(iSubTotal) ;
        
        String iTotal = String.format("Ksh %.2f", cTotal1 + cTax );
        jtxtTotal.setText(iTotal) ;
        
        String BarCode = String.format("Total is %.2f", cTotal1 + cTax );
        jtxtBarCode .setText(BarCode);
        
        
        
    }
    
    //=======================Function Change==================================================================
    public void Change()
    {
      double sum =0;
      double tax =0;
      double cash = Double.parseDouble(jtxtDisplay.getText()); 
      
       for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
       
       double cTax = (sum * 3.9)/100;
       double cChange = (cash - (sum + cTax));
       
       String ChangeGiven = String.format("Ksh %.2f",cChange);
       jtxtChange.setText(ChangeGiven);
       
    }
    
    
    
    
    
    
    
    
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit", "Point of Sale", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }    
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber.equals(""))
        {
         jtxtDisplay.setText(jbtn7.getText());
        }    
        else {
            Enternumber = jtxtDisplay.getText() + jbtn7.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber.equals(""))
        {
         jtxtDisplay.setText(jbtn8.getText());
        }    
        else {
            Enternumber = jtxtDisplay.getText() + jbtn8.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber.equals(""))
        {
         jtxtDisplay.setText(jbtn9.getText());
        }    
        else {
            Enternumber = jtxtDisplay.getText() + jbtn9.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber.equals(""))
        {
         jtxtDisplay.setText(jbtn4.getText());
        }    
        else {
            Enternumber = jtxtDisplay.getText() + jbtn4.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber.equals(""))
        {
         jtxtDisplay.setText(jbtn5.getText());
        }    
        else {
            Enternumber = jtxtDisplay.getText() + jbtn5.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber.equals(""))
        {
         jtxtDisplay.setText(jbtn6.getText());
        }    
        else {
            Enternumber = jtxtDisplay.getText() + jbtn6.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber.equals(""))
        {
         jtxtDisplay.setText(jbtn1.getText());
        }    
        else {
            Enternumber = jtxtDisplay.getText() + jbtn1.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber.equals(""))
        {
         jtxtDisplay.setText(jbtn2.getText());
        }    
        else {
            Enternumber = jtxtDisplay.getText() + jbtn2.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber.equals(""))
        {
         jtxtDisplay.setText(jbtn3.getText());
        }    
        else {
            Enternumber = jtxtDisplay.getText() + jbtn3.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber.equals(""))
        {
         jtxtDisplay.setText(jbtn0.getText());
        }    
        else {
            Enternumber = jtxtDisplay.getText() + jbtn0.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        
        if(! jtxtDisplay.getText().contains("."))
        {
           jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText()); 
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if(jcboPayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
        }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnpotatoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpotatoesActionPerformed
        double PriceOfItem = 80.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"potatoes", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnpotatoesActionPerformed

    private void jbtngreenapplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngreenapplesActionPerformed
        double PriceOfItem = 270.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"green apples", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtngreenapplesActionPerformed

    private void jbtngreencapsicumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngreencapsicumActionPerformed
        double PriceOfItem = 120.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"green capsicum", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtngreencapsicumActionPerformed

    private void jbtnimportedorangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimportedorangesActionPerformed
        double PriceOfItem = 250.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"oranges(imported)", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnimportedorangesActionPerformed

    private void jbtnlemonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlemonsActionPerformed
        double PriceOfItem = 180.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"lemons", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnlemonsActionPerformed

    private void jbtnlimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlimeActionPerformed
        double PriceOfItem = 180.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"lime", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnlimeActionPerformed

    private void jbtnmixedlettuceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmixedlettuceActionPerformed
        double PriceOfItem = 80.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"mixed lettuce", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnmixedlettuceActionPerformed

    private void jbtnpineapplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpineapplesActionPerformed
        double PriceOfItem = 90.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"pineapples", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnpineapplesActionPerformed

    private void jbtnredapplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnredapplesActionPerformed
        double PriceOfItem = 270.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"red apples", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnredapplesActionPerformed

    private void jbtnredcabbageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnredcabbageActionPerformed
        double PriceOfItem = 180.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"red cabbage", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnredcabbageActionPerformed

    private void jbtnredcapsicumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnredcapsicumActionPerformed
        double PriceOfItem = 280.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"red capsicum", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnredcapsicumActionPerformed

    private void jbtnredonionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnredonionActionPerformed
        double PriceOfItem = 100.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"red onions", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnredonionActionPerformed

    private void jbtnspringonionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnspringonionsActionPerformed
        double PriceOfItem = 150.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"spring onions", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnspringonionsActionPerformed

    private void jbtnstrawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnstrawberryActionPerformed
        double PriceOfItem = 240.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"strawberry", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnstrawberryActionPerformed

    private void jbtntomatoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntomatoesActionPerformed
        double PriceOfItem = 90.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"tomatoes", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtntomatoesActionPerformed

    private void jbtnwhitecabbageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnwhitecabbageActionPerformed
        double PriceOfItem = 50.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"white cabbage", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnwhitecabbageActionPerformed

    private void jbtnwhiteonionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnwhiteonionsActionPerformed
        double PriceOfItem = 150.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"white onions", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnwhiteonionsActionPerformed

    private void jbtnyellowcapsicumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnyellowcapsicumActionPerformed
        double PriceOfItem = 280.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"yellow capsicum", "1" ,PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnyellowcapsicumActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL, header,footer);
        }
        
        catch(java.awt.print.PrinterException e){
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         
         int RemoveItem = jTable1.getSelectedRow();
         if(RemoveItem >= 0)
         {
             model.removeRow(RemoveItem);
         }
         
        ItemCost();
        
        if(jcboPayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
        }
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JColorChooser jColorChooser4;
    private javax.swing.JColorChooser jColorChooser5;
    private javax.swing.JColorChooser jColorChooser6;
    private javax.swing.JColorChooser jColorChooser7;
    private javax.swing.JColorChooser jColorChooser8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtngreenapples;
    private javax.swing.JButton jbtngreencapsicum;
    private javax.swing.JButton jbtnimportedoranges;
    private javax.swing.JButton jbtnlemons;
    private javax.swing.JButton jbtnlime;
    private javax.swing.JButton jbtnmixedlettuce;
    private javax.swing.JButton jbtnpineapples;
    private javax.swing.JButton jbtnpotatoes;
    private javax.swing.JButton jbtnredapples;
    private javax.swing.JButton jbtnredcabbage;
    private javax.swing.JButton jbtnredcapsicum;
    private javax.swing.JButton jbtnredonion;
    private javax.swing.JButton jbtnspringonions;
    private javax.swing.JButton jbtnstrawberry;
    private javax.swing.JButton jbtntomatoes;
    private javax.swing.JButton jbtnwhitecabbage;
    private javax.swing.JButton jbtnwhiteonions;
    private javax.swing.JButton jbtnyellowcapsicum;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
